#include <random>
#include <iostream>
#include <string>

// The expression ARRAY_SIZE(a) is a compile-time constant of type
// size_t which represents the number of elements of the given
// array. You should only use ARRAY_SIZE on statically allocated
// arrays.
#ifndef ARRAY_SIZE
#define ARRAY_SIZE(a)                                   \
  ((sizeof(a) / sizeof(*(a))) /                         \
  static_cast<size_t>(!(sizeof(a) % sizeof(*(a)))))
#endif
 
int main()
{
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> dis(1, 0xFFFFFF);
 
    for (int n=0; n<100; ++n)
        //Use dis to transform the random unsigned int generated by gen into an int in [1, 6]
        std::cout << std::to_string(dis(gen)) << ' ';
    std::cout << '\n';
	
	int test[10];
	
	int size = ARRAY_SIZE(test);
	std::cout << " array size is:" << size;
}